//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "m_tree")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "m_tree_tree_index_index_in_tree_idx")]
    pub tree_index: i16,
    #[sea_orm(unique_key = "m_tree_tree_index_index_in_tree_idx")]
    pub index_in_tree: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub value: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
