{{- if .Values.secrets.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: network-secrets
  namespace: {{ include "status-network.namespace" . }}
  labels:
    {{- include "status-network.labels" . | nindent 4 }}
type: Opaque
stringData:
  BLOB_SUBMISSION_PRIVATE_KEY: "{{ .Values.network.signers.blobSubmission }}"
  AGGREGATION_PRIVATE_KEY: "{{ .Values.network.signers.aggregation }}"
  MESSAGE_ANCHORING_PRIVATE_KEY: "{{ .Values.network.signers.messageAnchoring }}"
  POSTMAN_L1_PRIVATE_KEY: "{{ .Values.network.signers.postmanL1 }}"
  POSTMAN_L2_PRIVATE_KEY: "{{ .Values.network.signers.postmanL2 }}"
  L1_RPC_ENDPOINT: "{{ include "status-network.l1RpcEndpoint" . }}"
  {{- if .Values.l2.rlnProver.privateKey }}
  RLN_PROVER_PRIVATE_KEY: "{{ .Values.l2.rlnProver.privateKey }}"
  {{- end }}
{{- end }}
