{{- if and .Values.l2.enabled .Values.l2.txExclusionApi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tx-exclusion-api-config-secret
  namespace: {{ include "status-network.namespace" . }}
  labels:
    {{- include "status-network.componentLabels" (list . "transaction-exclusion-api") | nindent 4 }}
type: Opaque
stringData:
  transaction-exclusion-app.config.toml: |
    data-queryable-window-since-rejected-timestamp="P7D"

    [database]
    schema="linea_transaction_exclusion"
    read_pool_size=10
    read_pipelining_limit=10
    transactional_pool_size=10
    [database.read]
    host="postgres"
    port="{{ .Values.l2.postgres.port }}"
    username="{{ .Values.l2.postgres.credentials.username }}"
    password="{{ .Values.l2.postgres.credentials.password }}"
    [database.write]
    host="postgres"
    port="{{ .Values.l2.postgres.port }}"
    username="{{ .Values.l2.postgres.credentials.username }}"
    password="{{ .Values.l2.postgres.credentials.password }}"
    [database.cleanup]
    polling-interval="PT60S"
    storage-period="P7D"
    [database.persistence-retry]
    backoff-delay = "PT5S"
    timeout = "PT20S"

    [api]
    port=8080
    path="/"
    number-of-verticles=1
    observability-port=8090

  vertx-options.json: |
    {
      "maxEventLoopExecuteTime": 30000000000,
      "maxWorkerExecuteTime": 120000000000
    }

  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO" monitorInterval="30">
      <Properties>
        <Property name="root.log.level">INFO</Property>
      </Properties>
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSSZZZ} | %t | %-5level | %c{1} | %msg%n"/>
        </Console>
      </Appenders>
      <Loggers>
        <Root level="${sys:root.log.level}">
          <AppenderRef ref="Console"/>
        </Root>
      </Loggers>
    </Configuration>
{{- end }}
