import { ethers } from "ethers";
import { RLN_CONFIG } from "./rln-config";

// Import ABIs - these should be generated by typechain
// For now, we'll use minimal ABIs for testing

const KARMA_ABI = [
  "function balanceOf(address account) view returns (uint256)",
  "function mint(address to, uint256 amount)",
  "function totalSupply() view returns (uint256)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
];

const RLN_ABI = [
  "function register(bytes32 identityCommitment, address userAddress)",
  "function members(uint256 index) view returns (bytes32)",
  "function users(address user) view returns (tuple(bytes32 identityCommitment, uint256 index))",
  "event MemberRegistered(address indexed user, bytes32 identityCommitment, uint256 index)",
];

const KARMA_TIERS_ABI = [
  "function getTier(uint256 karmaBalance) view returns (tuple(string name, uint256 minKarma, uint256 maxKarma, uint32 txPerEpoch))",
  "function updateTiers(tuple(string name, uint256 minKarma, uint256 maxKarma, uint32 txPerEpoch)[] tiers)",
  "event TiersUpdated()",
];

/**
 * Load deployed RLN contracts
 */
export function loadRlnContracts(provider: ethers.Provider, signer?: ethers.Signer) {
  const providerOrSigner = signer || provider;

  return {
    karma: new ethers.Contract(RLN_CONFIG.contracts.karma, KARMA_ABI, providerOrSigner),
    rln: new ethers.Contract(RLN_CONFIG.contracts.rln, RLN_ABI, providerOrSigner),
    karmaTiers: new ethers.Contract(RLN_CONFIG.contracts.karmaTiers, KARMA_TIERS_ABI, providerOrSigner),
  };
}

/**
 * Get contract addresses
 */
export function getContractAddresses() {
  return RLN_CONFIG.contracts;
}
