{{- if and .Values.l2.enabled .Values.services.l2RpcLoadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: l2-rpc-lb
  namespace: {{ include "status-network.namespace" . }}
  labels:
    {{- include "status-network.componentLabels" (list . "l2-rpc-lb") | nindent 4 }}
  {{- if .Values.services.l2RpcLoadBalancer.annotations }}
  annotations:
    {{- toYaml .Values.services.l2RpcLoadBalancer.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.l2RpcLoadBalancer.type }}
  ports:
    - name: http
      port: {{ .Values.services.l2RpcLoadBalancer.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "status-network.componentSelectorLabels" (list . "l2-node-besu") | nindent 4 }}
{{- end }}

{{- if and .Values.l1.enabled .Values.services.l1RpcLoadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: l1-rpc-lb
  namespace: {{ include "status-network.namespace" . }}
  labels:
    {{- include "status-network.componentLabels" (list . "l1-rpc-lb") | nindent 4 }}
  {{- if .Values.services.l1RpcLoadBalancer.annotations }}
  annotations:
    {{- toYaml .Values.services.l1RpcLoadBalancer.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.l1RpcLoadBalancer.type }}
  ports:
    - name: http
      port: {{ .Values.services.l1RpcLoadBalancer.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "status-network.componentSelectorLabels" (list . "l1-el-node") | nindent 4 }}
{{- end }}

{{- if and .Values.l2.enabled .Values.l2.postgresReplica.enabled .Values.services.postgresReplicaLoadBalancer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-lb
  namespace: {{ include "status-network.namespace" . }}
  labels:
    {{- include "status-network.componentLabels" (list . "postgres-replica-lb") | nindent 4 }}
  {{- if .Values.services.postgresReplicaLoadBalancer.annotations }}
  annotations:
    {{- toYaml .Values.services.postgresReplicaLoadBalancer.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.postgresReplicaLoadBalancer.type }}
  ports:
    - name: postgres
      port: {{ .Values.services.postgresReplicaLoadBalancer.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "status-network.componentSelectorLabels" (list . "postgres-replica") | nindent 4 }}
{{- end }}
