name: main

on:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  actions: read

jobs:
  sequencer-plugin-testing:
    uses: ./.github/workflows/linea-sequencer-plugin-testing.yml
    secrets: inherit