name: Testing CI

permissions:
  contents: read
  actions: read

on:
  workflow_call:
    inputs:
      postman_changed:
        required: true
        type: string
      transaction_exclusion_api_changed:
        required: true
        type: string
      linea_sequencer_changed:
        required: true
        type: string
      rln_prover_changed:
        required: true
        type: string

jobs:
  # Cache for pulling Docker images is disabled as we empirically found that this
  # (retrieving cache and loading Docker images) actually increased test time-to-completion
  postman:
    uses: ./.github/workflows/postman-testing.yml
    if: ${{ inputs.postman_changed == 'true' }}
    secrets: inherit

  transaction-exclusion-api:
    uses: ./.github/workflows/transaction-exclusion-api-testing.yml
    if: ${{ inputs.transaction_exclusion_api_changed == 'true' }}
    secrets: inherit

  linea-sequencer:
    uses: ./.github/workflows/linea-sequencer-plugin-testing.yml
    if: ${{ inputs.linea_sequencer_changed == 'true' }}
    secrets: inherit

  rln-prover:
    uses: ./.github/workflows/rln-prover-tests.yml
    if: ${{ inputs.rln_prover_changed == 'true' }}
    secrets: inherit

  # If all jobs are skipped, the workflow will still succeed.
  always_succeed:
    runs-on: ubuntu-latest
    if: ${{ inputs.postman_changed == 'false' && inputs.transaction_exclusion_api_changed == 'false' && inputs.linea_sequencer_changed == 'false' && inputs.rln_prover_changed == 'false' }}
    steps:
      - name: Ensure Workflow Success
        run: echo "All jobs were skipped, but workflow succeeds."
